name: ProtectoMyMobo # the plugins name as it should appear in the plugin list /pl
version: 1.0 # the plugin's version
author: Deano3663
main: McEssence.ProtectoMyMobo.Main
api-version: 1.18
commands:
  ProtectoMyMobo:
    description: ProtectoMyMobo
    usage: /ProtectoMyMobo
    permission: ProtectoMyMobo
  ProtectoMyMobo trust:
    description: trust a player
    usage: /ProtectoMyMobo trust (playerName)
    permission: ProtectoMyMobo.player.trust
  ProtectoMyMobo untrust:
    description: untrust a player
    usage: /ProtectoMyMobo untrust (playerName)
    permission: ProtectoMyMobo.player.untrust
  ProtectoMyMobo trustlist:
    description: list of trusted players
    usage: /ProtectoMyMobo trustlist
    permission: ProtectoMyMobo.player.trustlist
  ProtectoMyMobo reload:
    description: reload plugin
    usage: /ProtectoMyMobo reload
    permission: ProtectoMyMobo.admin.reload
  ProtectoMyMobo trustlistother:
    description: view a players trustlist
    usage: /ProtectoMyMobo trustlistother
    permission: ProtectoMyMobo.admin.trustlistother
permissions:
  ProtectoMyMobo.player.*:
    description: Gives access to all ProtectoMyMobo permissions
    children:
      ProtectoMyMobo.player.bypass: true
      ProtectoMyMobo.player.protect: true
      ProtectoMyMobo.player.trust: true
      ProtectoMyMobo.player.untrust: true
      ProtectoMyMobo.player.trustlist: true
  ProtectoMyMobo.admin.*:
    description: Gives access to all ProtectoMyMobo admin permissions
    children:
      ProtectoMyMobo.admin.reload: true
      ProtectoMyMobo.admin.trustlistother: true
  ProtectoMyMobo.player.bypass:
    description: Allows you to break other players protected blocks
    default: op
  ProtectoMyMobo.player.protect:
    description: Allows you to protect blocks
    default: op
  ProtectoMyMobo.player.trust:
    description: Allows you to trust a player
    default: op
  ProtectoMyMobo.player.untrust:
    description: Allows you to untrust a player
    default: op
  ProtectoMyMobo.player.trustlist:
      description: Allows you to see trusted players
      default: op
  ProtectoMyMobo.admin.reload:
    description: Allows you to reload ProtectoMyMobo configs
    default: op
  ProtectoMyMobo.admin.trustlistother:
    description: Allows you to view other peoples trustlist
    default: op